const assetOrder = {
  about: [
    "adicolor_ss2018.mp4",
    "berlin-3.JPG",
    "cursor.mp4",
    "dark.mp4",
    "houseofplants.mp4.mp4",
    "iceland-orig.mp4",
    "iceland_dribbble.jpg",
    "nike.mp4",
    "roadless.jpg",
    "soft-drinks.jpg",
    "tiles.jpg",
  ],
  projects: [
    "camera-culture.jpg",
    "ezgif.com-gif-to-mp4 (10).mp4",
    "ezgif.com-gif-to-mp4 (12).mp4",
    "fila_dribbble.jpg",
    "fullsize.mp4",
    "houseofplants_ar.mp4",
    "nz.jpg",
    "surf_fullsize.mp4",
    "surf_mob_fullsize.mp4",
  ],
  publications: [
    "When_To_Travel_Event_Loop_1080p.mp4.mp4",
    "asia-office.jpg",
    "certificate-when-to-travel-sotd.jpg",
    "ezgif.com-gif-to-mp4 (13).mp4",
    "ezgif.com-gif-to-mp4 (15).mp4",
    "kim.jpg",
    "office-move.mp4",
    "phototours.mp4",
    "skye_fullsize.mp4",
    "yosemite.mp4",
  ],
  experience: [
    "aperture-dribbble.jpg",
    "beaches_nodistort.mp4",
    "colour_01.jpg",
    "ezgif.com-gif-to-mp4 (16).mp4",
    "ezgif.com-gif-to-mp4 (17).mp4",
    "ezgif.com-gif-to-mp4 (18).mp4",
    "its-official-video.mp4",
    "skincare.jpg",
  ],
  education: [
    "botanical.jpg",
    "DSC05316.jpg",
    "botanical_dev.jpg",
    "cabin_fever.mp4",
    "coffeebag_shot.jpg",
    "mars-fullsize_1.mp4",
    "may-off.jpg",
    "off.jpg",
  ],
  skills: [
    "its-official-video.mp4",
    "GC Port_0046.jpg",
    "jekka_bottle.png",
    "GC Port_0666.jpg",
    "jekka_bottle_front_label.png",
    "jack.mp4",
    "plasticdreams_fullsize.mp4",
  ],
  contact: [
    "05.jpg",
    "6oclockgin (2).mp4",
    "melt].jpg",
    "luke.jpg",
    "natural_wonders.mp4.mp4",
    "IMG_9709 2.jpg",
    "sandsoftime.mp4.mp4",
  ],
};
export default assetOrder;
